from types import SimpleNamespace

from app.routes.school import _build_school_response_payload


def test_build_school_response_payload_includes_rating_stats():
    school = SimpleNamespace(
        id="SCH-1",
        user_id="USR-1",
        school_name="Sample School",
        school_type=None,
        school_medium=None,
        school_board=None,
        profile_pic_url=None,
        banner_pic_url=None,
        establishment_year=None,
        establishment_month=None,
        register_no=None,
        pin_code=None,
        block_division=None,
        district=None,
        state=None,
        country=None,
        school_email="principal@example.com",
        school_phone="9999999999",
        school_alt_phone=None,
        school_website=None,
        school_other_email=None,
        school_location=None,
        principal_name=None,
        principal_designation=None,
        principal_email=None,
        principal_phone=None,
        is_active=True,
        is_verified=True,
        account_type=None,
        is_business_approved=False,
        is_promotion_pending=False,
        created_at=None,
        institution_categories=None,
        hostel=None,
        computer_lab=None,
        medical_faculties=None,
        job_assurance=None,
        admission_process=None,
        internship=None,
        lms_facility=None,
        alumni_network=None,
        institution_class=None,
        library=None,
        available_classes=None,
        have_digital_board=None,
        have_cctv_in_campus=None,
        have_scholarship_opportunities=None,
        have_extra_curricular_activities=None,
        total_teachers=None,
        total_students=None,
        class_from=None,
        class_to=None,
        due_installment_type=None,
        transportation_facility=None,
        playground_facility=None,
        teaching_method=None,
        default_settlement_channel=None,
        created_by_admin=False,
        claim_status="unclaimed",
        claim_completed_at=None,
        attendance_qr_mark_in_token=None,
        attendance_qr_mark_out_token=None,
        followup_enabled=False,
        followup_days=None,
        followup_status=None,
        followup_note=None,
        followup_last_sent_at=None,
        followup_completed_at=None,
    )

    payload = _build_school_response_payload(
        school,
        is_authenticated=False,
        rating_count=3,
        average_rating=4.5,
    )

    assert payload["rating_count"] == 3
    assert payload["average_rating"] == 4.5
