"""replace exam.sections column with many-to-many relation

Revision ID: 0a0141b8250e
Revises: 436c8e536dea
Create Date: 2025-08-15 23:17:10.875156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a0141b8250e'
down_revision: Union[str, None] = '436c8e536dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_sections',
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('exam_id', 'section_id')
    )
    op.drop_column('exams', 'sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('sections', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_table('exam_sections')
    # ### end Alembic commands ###
