"""parent,present and permanet address table defined

Revision ID: 3fe5db03fd5f
Revises: 47d07e624b9f
Create Date: 2025-05-09 16:48:40.706662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe5db03fd5f'
down_revision: Union[str, None] = '47d07e624b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_table('permanent_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enter_pin', sa.String(length=10), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('building', sa.String(length=150), nullable=True),
    sa.Column('house_no', sa.String(length=50), nullable=True),
    sa.Column('floor_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_permanent_addresses_id'), 'permanent_addresses', ['id'], unique=False)
    op.create_table('present_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_this_permanent_as_well', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enter_pin', sa.String(length=10), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('building', sa.String(length=150), nullable=True),
    sa.Column('house_no', sa.String(length=50), nullable=True),
    sa.Column('floor_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_present_addresses_id'), 'present_addresses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_present_addresses_id'), table_name='present_addresses')
    op.drop_table('present_addresses')
    op.drop_index(op.f('ix_permanent_addresses_id'), table_name='permanent_addresses')
    op.drop_table('permanent_addresses')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_table('parents')
    # ### end Alembic commands ###
