"""add Exam model

Revision ID: 436c8e536dea
Revises: 934bea2af65b
Create Date: 2025-07-24 17:04:43.156929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436c8e536dea'
down_revision: Union[str, None] = '934bea2af65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('sections', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('chapters', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('exam_type', sa.Enum('MOCK', 'RANK', name='examtypeenum'), nullable=False),
    sa.Column('no_of_questions', sa.Integer(), nullable=False),
    sa.Column('pass_percentage', sa.Integer(), nullable=False),
    sa.Column('exam_activation_date', sa.DateTime(), nullable=False),
    sa.Column('inactive_date', sa.DateTime(), nullable=True),
    sa.Column('max_repeat', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'EXPIRED', 'DECLINED', name='examstatusenum'), nullable=False),
    sa.Column('no_students_appeared', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    # ### end Alembic commands ###
