"""Add created_at to <table>

Revision ID: 47fc31dc7f59
Revises: b244a006dc18
Create Date: 2025-05-26 15:36:05.838114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone
# revision identifiers, used by Alembic.
revision: str = '47fc31dc7f59'
down_revision: Union[str, None] = 'b244a006dc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_class_section_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'class_id', 'section_id', 'subject_id', name='unique_teacher_assignment')
    )
    op.create_index(op.f('ix_teacher_class_section_subjects_id'), 'teacher_class_section_subjects', ['id'], unique=False)
    op.add_column(
        'teachers',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text(
                f"'{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}'"
            ),
        ),
    )
    op.alter_column('teachers', 'created_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'created_at')
    op.drop_index(op.f('ix_teacher_class_section_subjects_id'), table_name='teacher_class_section_subjects')
    op.drop_table('teacher_class_section_subjects')
    # ### end Alembic commands ###
