"""Add school_id to timetable models

Revision ID: 4d0eb5c06f5d
Revises: 8f0cd332893d
Create Date: 2025-05-29 16:32:26.950183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0eb5c06f5d'
down_revision: Union[str, None] = '8f0cd332893d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_days', sa.Column('school_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'timetable_days', 'schools', ['school_id'], ['id'])
    op.add_column('timetable_periods', sa.Column('school_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'timetable_periods', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable_periods', type_='foreignkey')
    op.drop_column('timetable_periods', 'school_id')
    op.drop_constraint(None, 'timetable_days', type_='foreignkey')
    op.drop_column('timetable_days', 'school_id')
    # ### end Alembic commands ###
