"""create mcq_bank with correct exam_id

Revision ID: 5c3bbe849bfb
Revises: f6a56a710250
Create Date: 2025-08-16 16:20:57.374665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3bbe849bfb'
down_revision: Union[str, None] = 'f6a56a710250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcq_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('mcq_type', sa.String(length=1), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('option_a', sa.String(length=100), nullable=False),
    sa.Column('option_b', sa.String(length=100), nullable=False),
    sa.Column('option_c', sa.String(length=100), nullable=False),
    sa.Column('option_d', sa.String(length=100), nullable=False),
    sa.Column('correct_option', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcq_bank_id'), 'mcq_bank', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcq_bank_id'), table_name='mcq_bank')
    op.drop_table('mcq_bank')
    # ### end Alembic commands ###
