"""student and transport model created

Revision ID: 955de849ed51
Revises: 5e4f7ae54dbc
Create Date: 2025-05-08 18:24:10.521831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955de849ed51'
down_revision: Union[str, None] = '5e4f7ae54dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_name', sa.String(length=50), nullable=False, server_default='Unknown'),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('duty_start_time', sa.Time(), nullable=False),
    sa.Column('duty_end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transports_id'), 'transports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transports_id'), table_name='transports')
    op.drop_table('transports')
    # ### end Alembic commands ###
