"""add new field to student

Revision ID: a20595315a4a
Revises: 3fe5db03fd5f
Create Date: 2025-05-16 17:43:42.913067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20595315a4a'
down_revision: Union[str, None] = '3fe5db03fd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('school_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'students', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'school_id')
    # ### end Alembic commands ###
