"""Updated profile_pic and banner_pic in school

Revision ID: b244a006dc18
Revises: c07f989788f7
Create Date: 2025-05-21 12:03:47.575215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b244a006dc18'
down_revision: Union[str, None] = 'c07f989788f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('profile_pic_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('banner_pic_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'banner_pic_url')
    op.drop_column('schools', 'profile_pic_url')
    # ### end Alembic commands ###
