"""add pickup and drop stops

Revision ID: b386f04f2f29
Revises: a20595315a4a
Create Date: 2025-05-19 11:43:58.868590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b386f04f2f29'
down_revision: Union[str, None] = 'a20595315a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(length=100), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drop_stops_id'), 'drop_stops', ['id'], unique=False)
    op.create_table('pickup_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(length=100), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_stops_id'), 'pickup_stops', ['id'], unique=False)
    op.add_column('transports', sa.Column('vechicle_name', sa.String(length=50), nullable=False))
    op.add_column('transports', sa.Column('vechicle_number', sa.String(length=50), nullable=False))
    op.drop_column('transports', 'vehicle_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transports', sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('transports', 'vechicle_number')
    op.drop_column('transports', 'vechicle_name')
    op.drop_index(op.f('ix_pickup_stops_id'), table_name='pickup_stops')
    op.drop_table('pickup_stops')
    op.drop_index(op.f('ix_drop_stops_id'), table_name='drop_stops')
    op.drop_table('drop_stops')
    # ### end Alembic commands ###
