"""transport model updated

Revision ID: d09b73295763
Revises: 3bab1187c6a6
Create Date: 2025-05-08 19:04:06.637023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09b73295763'
down_revision: Union[str, None] = '3bab1187c6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transports', sa.Column('school_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'transports', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transports', type_='foreignkey')
    op.drop_column('transports', 'school_id')
    # ### end Alembic commands ###
