"""credit master table updated

Revision ID: e101a4303b63
Revises: a42e975bc8b7
Create Date: 2025-06-25 18:04:37.989943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e101a4303b63'
down_revision: Union[str, None] = 'a42e975bc8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_master', sa.Column('self_added_credit', sa.Integer(), nullable=True))
    op.add_column('credit_master', sa.Column('earned_credit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_master', 'earned_credit')
    op.drop_column('credit_master', 'self_added_credit')
    # ### end Alembic commands ###
