"""Add category scores to school_ratings

Revision ID: fa70edb0e479
Revises: f3113f309b1c
Create Date: 2026-09-15 18:57:22.497075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa70edb0e479'
down_revision: Union[str, None] = 'f3113f309b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_ratings', sa.Column('infrastructure', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('value_for_fee', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('teaching_quality', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('academic_results', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('placement_support', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('industrial_training', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('extracurricular', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('student_alumni', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('hostel_and_foods', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('transportation', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('safety_and_discipline', sa.SmallInteger(), nullable=True))
    op.add_column('school_ratings', sa.Column('management', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_ratings', 'management')
    op.drop_column('school_ratings', 'safety_and_discipline')
    op.drop_column('school_ratings', 'transportation')
    op.drop_column('school_ratings', 'hostel_and_foods')
    op.drop_column('school_ratings', 'student_alumni')
    op.drop_column('school_ratings', 'extracurricular')
    op.drop_column('school_ratings', 'industrial_training')
    op.drop_column('school_ratings', 'placement_support')
    op.drop_column('school_ratings', 'academic_results')
    op.drop_column('school_ratings', 'teaching_quality')
    op.drop_column('school_ratings', 'value_for_fee')
    op.drop_column('school_ratings', 'infrastructure')
    # ### end Alembic commands ###
